### ISSUE TITLE
Expose All Templates in Monitoring Studio to be automatically OpenAPI & Swagger UI compatible

### ISSUE THREAD

**Issue by abhijitpramanik** [sentrysoftware/studioX-templates#50]
Hello Team / @bertysentry ,

From the point of view of an enduser using your templates, after the import of the specific templates, I would really like to know all the API calls (GET/POST/PUT) exposed in termes of monitoring.

Let's say if we are monitoring a dellEmcViprController. I would like to know all the GET API calls for this storage system in order to leverage only the calls, I would require for my monitoring need. 

For Example - I am more interested in :  
`https://%{HOSTNAME}:%{PORT}/monitor/stats.json`
and not really interested in : 
`https://%{HOSTNAME}:%{PORT}/control/db/consistency.json`

By making the templates compatible with OpenAPI/Swagger UI, I can simply plug the specific template to my swagger eco-system and anyone can see the different API exposed,quickly test it with adequate response code as output (200,302,401) and take what fits the best. Please see email of screenshot attached for a simple GET call on /fruits.

Just a thought. :)
Cheers,
Abhi.
![fruits-GET](https://user-images.githubusercontent.com/30588915/115373742-739cfa80-a1cc-11eb-9383-71a1f4766414.png)

**Comment by bertysentry** [comment]
That's a good point, @abhijitpramanik 

We want to build a sort of automatic documentation of our templates, that would list all of the calls made by each template, so the user can easily see what is being done.

Maybe in version 10.4 of Monitoring Studio! (it's not planned for 10.3 which will be released next month)

I hope you're doing well! How come you're using Monitoring Studio?! 😁

**Comment by abhijitpramanik** [comment]
So Cool @bertysentry, if you have already noted this in your piepline for the 10.4 version 👍 

I am doing well and hope the same for you !! 😊 
I was just going through the github of sentrysoftware and after seeing all the different repos, this came to me as a thought. Not using Monitoring Studio as of now, but wish I was, as it is a complete toolset. 😍 

Cheers
