### ISSUE TITLE
Template issues with hitachi-hcp

### ISSUE THREAD

**Issue by seanzhang0711** [sentrysoftware/studioX-templates#84]
Template nam:hitachi-hcp
hcpNodes-sanStatus This is the status of which san? Since I added it, the status has been reporting abnormal alarms
Is there a reference document for this?
Thanks!

**Comment by RazeemM** [comment]
It interprets the status of the SAN path.
 INTEGER {error(0), rain(1), sanWithoutMultipath(2), sanGood(3), sanDegradedToOne(4)}
Refer to the SNMP MIB of the HCP for more details on the metrics collected.
http://www.circitor.fr/Mibs/Html/H/HCP-MIB.php

**Comment by seanzhang0711** [comment]
Thank you for your reply
I can't open this URL. Could you please send this mib file to my email?
seanzhang0711@163.com

**Comment by RazeemM** [comment]
Can you provide the customer company's name? You would need storage licenses to monitor HCP with Monitoring Studio.
